elasticsearch:
  build: elasticsearch/
  container_name: elasticsearch
  command: elasticsearch -Des.network.host=0.0.0.0
  ports:
    - "9200:9200"
logstash:
    build: logstash/
    container_name: logstash
    command: logstash -f /etc/logstash/conf.d/logstash.conf
    volumes:
        - ./logstash/config:/etc/logstash/conf.d
    ports:
        - "5000:5000"
    links:
        - elasticsearch
kibana:
    build: kibana/
    container_name: kibana
    volumes:
        - ./kibana/config/kibana.yml:/opt/kibana/config/kibana.yml
    ports:
        - "5601:5601"
    links:
        - elasticsearch
