FROM logstash:latest


RUN logstash-plugin install logstash-input-kafka
RUN logstash-plugin install logstash-output-kafka
# Add your logstash plugins setup here
# Example: RUN logstash-plugin install logstash-filter-json
